# Generated by Django 3.2.3 on 2021-06-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('length', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('favorited', models.ManyToManyField(to='main_app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('attendees', models.ManyToManyField(to='main_app.Profile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_hikes', to='main_app.profile')),
                ('trail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_hikes', to='main_app.trail')),
            ],
        ),
    ]
